name: Build and Release Canary

on: pull_request

jobs:

  build-and-publish-canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - run: echo "ref ${{ github.ref }}"
      - run: echo "head_ref ${{ github.head_ref }}"
      - run: echo "base_ref ${{ github.base_ref }}"
      - name: switch to actual pr branch
        run: git checkout -b ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          scope: test
          registry-url: 'https://npm.pkg.github.com'
#      - run: npm ci
#      - run: npm run bootstrap
#      - name: Build
#        run: npm run build
      - name: Publish canary version
        env:
          GH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          NPM_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: npx auto canary --force
