#name: Test Code
#
#on:
#  push:
#
#jobs:
#
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 12
#      - run: npm ci
#      - name: set creds for GPR
#        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.AUTH_TOKEN }}
#      - run: npm run bootstrap
#      - run: npm test
